### ISSUE TITLE
missing link to http://fwtwr.com/18xx/rules_difference_list/index.htm

### ISSUE THREAD

**Issue by yzemaze** [18xx/union-station#1]
As it’s **the** masterlist I’d definitely include a link to it and an acknowledgement of their work.
btw: "recent changes" there don’t always reflect the latest changes. So you might want to scrape the page regularly or even better cooperate with Keith Thomasson to keep you in the loop.

[I’ve sent a few corrections regarding 18CZ last week (2.7, 7.4, 7.6, 7.7, 9.1). He implemented them and obviously changed the (c) date, but did not update "recent changes".]

**Comment by gmacdougall** [comment]
I will add this in. The site as it stands now is mostly a tech demo.  The rules differences are a different way of organizing things by game that I was always interested in.

I'll shoot Keith an e-mail to see if he's interested in collaborating. Thanks for the suggestion!

**Comment by yzemaze** [comment]
Sure, but a useful demo (if you add > 5.x and keep it up to date).
I’m actually glad you do this. I thought about compiling differences on a per game basis myself, but then stumbled upon your site ;)

**Comment by gmacdougall** [comment]
I've removed the rules differences due to lack of interest in finishing it. This is no longer relevant.
